Repository evgshk/nest-egg, pull requests merged in 2019-07, with the labels that each got.

#1 Add - new project, full-layout, dashboard component
  .editorconfig
  .gitignore
  angular.json
  browserslist
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.e2e.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/containers/full-layout/full-layout.component.html
  src/app/containers/full-layout/full-layout.component.scss
  src/app/containers/full-layout/full-layout.component.ts
  src/app/containers/full-layout/full-layout.module.ts
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
  src/assets/.gitkeep
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/karma.conf.js
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/styles/customize-and-design.less
  src/test.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  src/tslint.json
  tsconfig.json
  tslint.json
Labels: good first issue

#4 Add - adopted sider for table and mobile modes
  package-lock.json
  src/app/containers/full-layout/full-layout.component.html
  src/app/containers/full-layout/full-layout.component.scss
  src/app/containers/full-layout/full-layout.component.ts
  src/app/containers/full-layout/full-layout.module.ts
  src/styles/customize-and-design.less
Labels: enhancement

#8 PR Update README.md
  README.md
Labels: documentation

#12 Fix - bootstrap, locales, code-style, fb-config #11
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/containers/full-layout/full-layout.component.html
  src/app/shared/models/currency.model.ts
  src/app/shared/models/exchange-rate.model.ts
  src/app/shared/models/index.ts
  src/app/shared/models/saving-totals.model.ts
  src/app/shared/models/saving.model.ts
  src/app/shared/services/abstract.service.ts
  src/app/shared/services/base.service.ts
  src/app/shared/services/firebase.service.ts
  src/app/shared/services/firebase/firebase.service.ts
  src/app/shared/services/firebase/index.ts
  src/app/shared/services/index.ts
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/environments/firebaseConfig.ts
  src/styles/custom-styles.scss
  src/styles/customize-and-design.less
  src/styles/customize-bootstrap.scss
  tsconfig.json
Labels: infrastructure

#15 Fix - resolve rebase conflicts, fix code styles, some non-business fixes
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shared/models/index.ts
  src/app/shared/models/user.model.ts
  src/app/shared/services/auth/auth-guard.service.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/auth/index.ts
  src/app/shared/services/index.ts
  src/app/shared/services/user/index.ts
  src/app/shared/services/user/user.service.ts
  src/app/views/login/login.component.html
  src/app/views/login/login.component.ts
  src/app/views/user/user.component.html
  src/app/views/user/user.component.ts
  src/app/views/user/user.resolver.ts
Labels: 2, enhancement

#16 PR Initialize firebase deploy configuration
  .firebaserc
  firebase.json
Labels: infrastructure

#41 PR Change global spinner style #40
  src/app/components/app-spinner/app-spinner.component.html
  src/app/components/app-spinner/app-spinner.component.scss
Labels: 1

#42 Add - reusable reactive forms/validation/etc, improved login form
  src/app/app.module.ts
  src/app/components/app-reactive/reactive-directives/index.ts
  src/app/components/app-reactive/reactive-directives/on-input-value-control.directive.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/label/index.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/label/reactive-label.component.html
  src/app/components/app-reactive/reactive-form/additional-decorations/label/reactive-label.component.scss
  src/app/components/app-reactive/reactive-form/additional-decorations/label/reactive-label.component.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/sub-label/index.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/sub-label/reactive-sub-label.component.html
  src/app/components/app-reactive/reactive-form/additional-decorations/sub-label/reactive-sub-label.component.scss
  src/app/components/app-reactive/reactive-form/additional-decorations/sub-label/reactive-sub-label.component.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/validation-message/index.ts
  src/app/components/app-reactive/reactive-form/additional-decorations/validation-message/validation-message.component.html
  src/app/components/app-reactive/reactive-form/additional-decorations/validation-message/validation-message.component.scss
  src/app/components/app-reactive/reactive-form/additional-decorations/validation-message/validation-message.component.ts
  src/app/components/app-reactive/reactive-form/app-reactive-abstract.component.ts
  src/app/components/app-reactive/reactive-form/app-reactive-forms.module.ts
  src/app/components/app-reactive/reactive-form/index.ts
  src/app/components/app-reactive/reactive-form/reactive-check-box/index.ts
  src/app/components/app-reactive/reactive-form/reactive-check-box/reactive-check-box.component.html
  src/app/components/app-reactive/reactive-form/reactive-check-box/reactive-check-box.component.ts
  src/app/components/app-reactive/reactive-form/reactive-input/index.ts
  src/app/components/app-reactive/reactive-form/reactive-input/reactive-input.component.html
  src/app/components/app-reactive/reactive-form/reactive-input/reactive-input.component.ts
  src/app/components/app-reactive/reactive-functions/validation.ts
  src/app/components/app-reactive/reactive-lists/messages.ts
  src/app/components/app-reactive/reactive-lists/patterns.ts
  src/app/components/app-reactive/reactive-pipes/index.ts
  src/app/components/app-reactive/reactive-pipes/value-transform.pipe.ts
  src/app/views/auth/login/login.component.html
  src/app/views/auth/login/login.component.scss
  src/app/views/auth/login/login.component.ts
  src/app/views/auth/login/login.module.ts
Labels: 2
